add and fetch users
slawomircieslinski/hublsoft-login pull request #3
Opened 2020-09-29 21:53 UTC by goofballLogic

2020-10-01 09:06 UTC, slawomircieslinski requested changes
I'm getting  415 unsupported media type for https://localhost:5001/users/1

2020-10-01 09:09 UTC, goofballLogic commented
> I'm getting 415 unsupported media type for https://localhost:5001/users/1

thanks - should be fixed now

2020-10-01 10:10 UTC, slawomircieslinski approved these changes

2020-10-01 13:35 UTC, goofballLogic commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            else if (Request.Method == "PUT")
thanks - POST would be better here.

2020-10-01 13:41 UTC, slawomircieslinski commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            if (Request.Method == "GET")
Why Request.Method decide which sp should be called, what if we have to call GetUserAudit or DeleteUser

2020-10-01 13:56 UTC, goofballLogic commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            if (Request.Method == "GET")
What would a better solution be for those?

2020-10-01 14:52 UTC, slawomircieslinski commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            if (Request.Method == "GET")
Maybe Routing. We can match URLs of incoming requests and map them to actions?

2020-10-01 15:03 UTC, goofballLogic commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            if (Request.Method == "GET")
ok let me put another version in and see what you think

2020-10-01 15:55 UTC, goofballLogic commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            if (Request.Method == "GET")
Ok I have added in the Delete user method (although not the GetUserAudit one yet). I also have three methods (lines 14, 17, 20) which correspond to each route. Is that what you were thinking?

2020-10-02 09:58 UTC, slawomircieslinski commented on Hubl.LoginAPI/Hubl.LoginAPI/UsersController.cs
> +            if (Request.Method == "GET")
Something like this, I even added GetUserAudit
https://github.com/slawomircieslinski/hublsoft-login/compare/login-API...Amethyst#diff-849319779895a0ba7c576a67c75f8a97

2020-10-02 14:27 UTC, merged